// Code generated by protoc-gen-messageintegrity. DO NOT EDIT.
// versions:
//  protoc-gen-messageintegrity	v0.1.0
//  protoc						v3.13.0
// source: integrity/v1/steering_command_example.proto.

package verification

import (
	"github.com/einride/protoc-gen-messageintegrity/internal/verification"
	"os"
)

const ImplicitMessageIntegrityKey = "IMPLICIT_MESSAGE_INTEGRITY_KEY"

func (x *SteeringCommandVerification) Sign() error {
	key := os.Getenv(ImplicitMessageIntegrityKey)
	return verification.SignProto(x, []byte(key))
}

func (x *SteeringCommandVerification) Verify() (bool, error) {
	key := os.Getenv(ImplicitMessageIntegrityKey)
	return verification.ValidateHMAC(x, []byte(key))
}
